# Generated by Django 4.2.26 on 2026-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenseshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Divide Equally'), ('custom', 'Custom Split')], default='equal', max_length=10),
        ),
    ]
